SeattleRobotics/ftc_app

FtcRobotController/build.gradle
TeamCode/build.gradle
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahMotorTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Minimal changes required to get ftc_propject working with latest version of build tools, and added a test OpMode.

Merge changes from coolguybri: Initial setup of ftc_project

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ClawTest.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahCalibration.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahMotorTest.java

Merge changes from coolguybri

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CrazyAngle.java

Wrote up CrazyAngle conversions

CrazyAngle

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CrazyAngle.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahChassis.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahNavigation.java

Merge this weeks changes from the mac laptop

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRun2.java

merge fromflynn

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CrazyAngle.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahNavigation.java

Merge from Audrey

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRun4.java

BullRun2 now moves all the way to the edge before turning and moving to the crater.

BullRun2 move to edge

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahNavigation.java

All starting positions have more user friendly names and the team name
now prints without a prompt from the controller

Renamed starting positions and it now prints the team

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRunChaChaCha.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRunChaChaCha4.java

checking in work-in-progresss before first competition

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/JoeSquishyChassis.java

merge to main

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRun4.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BullRunChaChaCha4.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeamMarkerRun.java

Changes to Bullrun4, Chachacha4, and TeamMarkerrun

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ChassisConfig.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahBullRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeBullRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverBullRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StandardChassis.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeamMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeamMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/VuforiaSTART.java

Merge from Flynn

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BigSwingController.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverController.java

Tested and edited controllers.

Edited Controllers

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverController.java

Cleaned up the controller aswell as fixing up a few small things

Edited Quicksilver Controller

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StandardChassis.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeamMarkerRun.java

merge from mac laptop

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverController.java

quicksilver updates for servos

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ChassisConfig.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/DescendFromLander.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeController.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverDescendFromLander.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StandardChassis.java

emergency checkin for moving laptops

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeController.java

Q-S Detection

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AllInOne.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ClawTest.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/FourWheelsTwoControllers.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/JoeSquishyChassis.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahBullRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahChaChaCha.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahMarkerRun.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MallahMarkerRun2.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahCalibration.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahChassis.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahMotorTest.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MonsieurMallahNavigation.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PhatSwipeController.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverController.java

Edited out all unnecessary OpModes. Took out presets for Quicksilver

Last Minute Edits

---

TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ChassisConfig.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ChickenSquat.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/QuickSilverController.java
TeamCode/src/main/java/org/firstinspires/ftc/teamcode/StandardChassis.java

Got Chicken Squat working with the new arm, hence getting the descend from lander code working aswell.
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

Chicken Squat
